defaultCurrency: "money"

vault:
  fractionalDigits: 2
  plural: "$"
  singular: "$"

currencies:
  money:
    name: "小钱钱"
    type: inkdb
    properties:
      storage: "plugins/AnkhEconomy/money.idb"
      prefix: "ankh-economy.money."